/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResponse { 
    /**
     * JWT bearer token
     */
    token: string;
    /**
     * JWT refresh token
     */
    refreshToken: string;
}

