/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Categoría temática de las revistas (JCR).
 */
export interface CategoryResponse { 
    id: string;
    /**
     * Nombre de la categoría.
     */
    name: string;
    /**
     * Edición del JCR a la que pertenece la categoría (p. ej. SCIE, SSCI).
     */
    edition?: string;
}

