/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicationStatus } from './publicationStatus';


/**
 * Nuevo estado de la publicación. Solo se permiten transiciones válidas del ciclo de vida de la publicación.
 */
export interface ChangePublicationStatusRequest { 
    status: PublicationStatus;
}
export namespace ChangePublicationStatusRequest {
}


