/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateGroupRequest { 
    /**
     * El nombre del grupo de investigación. Debe ser único.
     */
    name: string;
    /**
     * Descripción detallada de las actividades del grupo.
     */
    description?: string;
}

