/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicationAuthorInput } from './publicationAuthorInput';
import { PublicationStatus } from './publicationStatus';


export interface CreatePublicationRequest { 
    /**
     * Título de la publicación. Obligatorio.
     */
    title: string;
    /**
     * Grupo de investigación al que pertenece la publicación. El creador debe ser miembro.
     */
    groupId: string;
    /**
     * Journal al que se asocia la publicación.
     */
    journalId: string;
    /**
     * Resumen de la publicación.
     */
    'abstract'?: string;
    /**
     * DOI de la publicación. Solo permitido cuando el estado es PUBLISHED.
     */
    doi?: string;
    status?: PublicationStatus;
    /**
     * Co-autores de la publicación, en orden. El creador se añade siempre como primer autor interno.
     */
    authors?: Array<PublicationAuthorInput>;
}
export namespace CreatePublicationRequest {
}


