/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorResponse { 
    /**
     * Error message for the developer
     */
    message: string;
    /**
     * i18n code
     */
    code: string;
    /**
     * Parameters for the i18n code
     */
    params?: { [key: string]: any; };
}

