/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicationCreatorResponse } from './publicationCreatorResponse';
import { PublicationStatus } from './publicationStatus';


/**
 * Publicación dentro del listado de un grupo. Igual que PublicationSummaryResponse pero enriquecida con el creador (dueño) para mostrar de quién es cada publicación.
 */
export interface GroupPublicationSummaryResponse { 
    id: string;
    title: string;
    groupId: string;
    journalId: string;
    /**
     * Nombre del journal asociado.
     */
    journalName?: string;
    status: PublicationStatus;
    createdAt: string;
    /**
     * Fecha en que la publicación pasó a su estado actual.
     */
    statusChangedAt: string;
    creator: PublicationCreatorResponse;
}
export namespace GroupPublicationSummaryResponse {
}


