/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupRole } from './groupRole';


export interface GroupSummaryResponse { 
    id: string;
    /**
     * Group name.
     */
    name: string;
    /**
     * Group description.
     */
    description?: string;
    role: GroupRole;
    /**
     * Number of members in the group.
     */
    memberCount: number;
    /**
     * Whether the user is the owner of the group.
     */
    isOwner: boolean;
}
export namespace GroupSummaryResponse {
}


