/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupRole } from './groupRole';


export interface GroupMemberDetail { 
    /**
     * Unique identifier of the user.
     */
    userId: string;
    /**
     * First name of the user.
     */
    firstName: string;
    /**
     * Last name of the user.
     */
    lastName: string;
    /**
     * Email of the user.
     */
    email: string;
    role: GroupRole;
    /**
     * URL of the user\'s profile image.
     */
    profileImageUrl?: string;
    /**
     * Whether the user is the creator of the group.
     */
    isCreator: boolean;
}
export namespace GroupMemberDetail {
}


