/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A summary of the group where the user is invited.
 */
export interface GroupInvitationSummary { 
    /**
     * The unique identifier of the group
     */
    groupId: string;
    /**
     * The name of the group
     */
    groupName: string;
}

