/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupMemberDetail } from './groupMemberDetail';


export interface GroupDetailResponse { 
    id: string;
    name: string;
    description?: string;
    createdBy: string;
    createdAt: string;
    members: Array<GroupMemberDetail>;
}

