/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupJournalInterestResponse } from './groupJournalInterestResponse';


/**
 * Página con la unión de revistas de interés de los miembros del grupo.
 */
export interface GroupJournalInterestPageResponse { 
    content: Array<GroupJournalInterestResponse>;
    /**
     * Número total de revistas en la unión.
     */
    totalElements: number;
    /**
     * Número total de páginas.
     */
    totalPages: number;
    /**
     * Índice de página actual (base 0).
     */
    page: number;
    /**
     * Tamaño de página solicitado.
     */
    size: number;
}

