/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GroupRole = {
    Member: 'MEMBER',
    Admin: 'ADMIN'
} as const;
export type GroupRole = typeof GroupRole[keyof typeof GroupRole];

