/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JournalCategoryQuartileSummary } from './journalCategoryQuartileSummary';
import { GroupJournalInterestMember } from './groupJournalInterestMember';


/**
 * Revista marcada como de interés por uno o más miembros del grupo.
 */
export interface GroupJournalInterestResponse { 
    id: string;
    name: string;
    issn?: string;
    eIssn?: string;
    publisherName?: string;
    /**
     * Año del informe del que provienen las categorías/cuartiles mostrados.
     */
    year?: number;
    /**
     * Categorías/cuartiles de la revista en su último año disponible.
     */
    categories: Array<JournalCategoryQuartileSummary>;
    /**
     * Número de miembros del grupo que han marcado esta revista como de interés.
     */
    favoriteCount: number;
    /**
     * Miembros del grupo que han marcado esta revista como de interés.
     */
    members: Array<GroupJournalInterestMember>;
}

