/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupInvitationSummary { 
    /**
     * The unique identifier of the group
     */
    groupId?: string;
    /**
     * The name of the group
     */
    groupName?: string;
}

