/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Miembro del grupo que ha marcado la revista como de interés.
 */
export interface GroupJournalInterestMember { 
    /**
     * Unique identifier of the member.
     */
    userId: string;
    /**
     * First name of the member.
     */
    firstName: string;
    /**
     * Last name of the member.
     */
    lastName: string;
    /**
     * URL of the member\'s profile image.
     */
    profileImageUrl: string;
}

