/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A summary of the inviter.
 */
export interface InviterSummary { 
    /**
     * The unique identifier of the inviter
     */
    id: string;
    /**
     * The first name of the inviter
     */
    firstName: string;
    /**
     * The last name of the inviter
     */
    lastName: string;
    /**
     * The URL of the profile image of the inviter
     */
    profileImageUrl: string;
}

