/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvitableUserResponse { 
    /**
     * Unique identifier of the user.
     */
    id: string;
    /**
     * First name of the user.
     */
    firstName: string;
    /**
     * Last name of the user.
     */
    lastName: string;
    /**
     * Email of the user.
     */
    email: string;
    /**
     * URL of the user\'s profile image.
     */
    profileImageUrl: string;
}

