/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InviterSummary } from './inviterSummary';
import { GroupInvitationSummary } from './groupInvitationSummary';


/**
 * The response containing the invitation details.
 */
export interface InvitationResponse { 
    /**
     * The unique identifier of the invitation
     */
    id: string;
    group: GroupInvitationSummary;
    inviter: InviterSummary;
    /**
     * The date and time the invitation was created
     */
    createdAt: string;
}

