/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JournalCategoryQuartileSummary } from './journalCategoryQuartileSummary';


/**
 * Revista con su posición de categorías/cuartiles en su último año disponible.
 */
export interface JournalSummaryResponse { 
    id: string;
    name: string;
    issn?: string;
    eIssn?: string;
    publisherName?: string;
    /**
     * Año del informe del que provienen las categorías/cuartiles mostrados.
     */
    year?: number;
    /**
     * Categorías/cuartiles de la revista en su último año disponible.
     */
    categories: Array<JournalCategoryQuartileSummary>;
}

