/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Quartile } from './quartile';


/**
 * Posición de una revista en una categoría para un año concreto.
 */
export interface JournalCategoryQuartileSummary { 
    categoryId: string;
    categoryName: string;
    edition?: string;
    quartile: Quartile;
    /**
     * Factor de impacto en esa categoría/año.
     */
    impactFactor?: number;
}
export namespace JournalCategoryQuartileSummary {
}


