/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Quartile } from './quartile';


/**
 * Posición de la revista en una categoría para un año (vista de detalle).
 */
export interface JournalCategoryQuartileDetail { 
    year: number;
    categoryName: string;
    edition?: string;
    quartile: Quartile;
    impactFactor?: number;
}
export namespace JournalCategoryQuartileDetail {
}


