/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Estado del proceso de sincronización de journals con Clarivate.
 */
export interface JournalSyncStatusResponse { 
    /**
     * Estado actual del volcado.
     */
    status: JournalSyncStatusResponse.StatusEnum;
    /**
     * Número de journals procesados en el run actual.
     */
    processedCount: number;
    /**
     * Número total de journals a procesar (si se conoce).
     */
    totalCount?: number;
    /**
     * Número de journals que fallaron en el run actual.
     */
    failedCount: number;
    /**
     * Última fecha de actualización conocida de los datos de Clarivate.
     */
    clarivateLastUpdated?: string;
    /**
     * Inicio del run actual o último.
     */
    runStartedAt?: string;
    /**
     * Fin del último run completado.
     */
    runFinishedAt?: string;
}
export namespace JournalSyncStatusResponse {
    export const StatusEnum = {
        Idle: 'IDLE',
        Running: 'RUNNING',
        Success: 'SUCCESS',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


