/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JournalCategoryQuartileDetail } from './journalCategoryQuartileDetail';
import { JournalMetricResponse } from './journalMetricResponse';


/**
 * Detalle completo de una revista con sus métricas y cuartiles por año/categoría.
 */
export interface JournalDetailResponse { 
    id: string;
    name: string;
    issn?: string;
    eIssn?: string;
    publisherName?: string;
    publisherCountry?: string;
    metrics: Array<JournalMetricResponse>;
    categoryQuartiles: Array<JournalCategoryQuartileDetail>;
}

