/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JournalSummaryResponse } from './journalSummaryResponse';


/**
 * Página de resultados de la búsqueda de revistas.
 */
export interface JournalSearchPageResponse { 
    content: Array<JournalSummaryResponse>;
    /**
     * Número total de revistas que cumplen los filtros.
     */
    totalElements: number;
    /**
     * Número total de páginas.
     */
    totalPages: number;
    /**
     * Índice de página actual (base 0).
     */
    page: number;
    /**
     * Tamaño de página solicitado.
     */
    size: number;
}

