/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Métrica anual de una revista.
 */
export interface JournalMetricResponse { 
    year: number;
    impactFactor?: number;
}

