/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Miembros que ocultan su historial de publicaciones al usuario actual.
 */
export interface MembersHiddenFromMeResponse { 
    /**
     * Ids de los miembros cuyas publicaciones no se muestran al usuario actual.
     */
    hiddenMemberIds: Array<string>;
}

