/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicationSummaryResponse } from './publicationSummaryResponse';


/**
 * Página de resultados del historial de publicaciones.
 */
export interface PublicationListPageResponse { 
    content: Array<PublicationSummaryResponse>;
    /**
     * Número total de publicaciones que cumplen los filtros.
     */
    totalElements: number;
    /**
     * Número total de páginas.
     */
    totalPages: number;
    /**
     * Índice de página actual (base 0).
     */
    page: number;
    /**
     * Tamaño de página solicitado.
     */
    size: number;
}

