/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Creador (dueño) de la publicación.
 */
export interface PublicationCreatorResponse { 
    userId: string;
    firstName: string;
    lastName: string;
    /**
     * URL de la imagen de perfil del creador.
     */
    profileImageUrl?: string;
}

