/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Autor de entrada. Para un co-autor interno se indica únicamente userId; para un co-autor externo se indican firstName y lastName.
 */
export interface PublicationAuthorInput { 
    /**
     * Identificador del usuario registrado (co-autor interno).
     */
    userId?: string;
    /**
     * Nombre del co-autor externo.
     */
    firstName?: string;
    /**
     * Apellidos del co-autor externo.
     */
    lastName?: string;
}

