/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicationStatus } from './publicationStatus';


/**
 * Entrada del historial de estados de una publicación. Representa el momento en que la publicación pasó a un estado concreto, junto con el journal asociado en ese momento (útil para reflejar el journal anterior en un reenvío) y un comentario opcional.
 */
export interface PublicationStatusHistoryEntry { 
    status: PublicationStatus;
    /**
     * Journal asociado a la publicación en el momento de esta transición.
     */
    journalId: string;
    /**
     * Nombre del journal asociado en el momento de esta transición.
     */
    journalName?: string;
    /**
     * Fecha y hora en que la publicación pasó a este estado.
     */
    changedAt: string;
    /**
     * Comentario opcional asociado a la transición.
     */
    comment?: string;
}
export namespace PublicationStatusHistoryEntry {
}


