/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicationAuthorType } from './publicationAuthorType';


/**
 * Autor de una publicación, interno (usuario registrado) o externo.
 */
export interface PublicationAuthorResponse { 
    /**
     * Identificador de la entrada de autoría dentro de la publicación.
     */
    authorId: string;
    type: PublicationAuthorType;
    /**
     * Identificador del usuario registrado. Solo presente en autores internos.
     */
    userId?: string;
    firstName: string;
    lastName: string;
    /**
     * Solo presente en autores internos.
     */
    email?: string;
    /**
     * URL de la imagen de perfil. Solo presente en autores internos.
     */
    profileImageUrl?: string;
}
export namespace PublicationAuthorResponse {
}


