/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicationStatus } from './publicationStatus';


export interface PublicationSummaryResponse { 
    id: string;
    title: string;
    groupId: string;
    journalId: string;
    /**
     * Nombre del journal asociado.
     */
    journalName?: string;
    status: PublicationStatus;
    createdAt: string;
    /**
     * Fecha en que la publicación pasó a su estado actual.
     */
    statusChangedAt: string;
}
export namespace PublicationSummaryResponse {
}


