/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicationVisibilityMember } from './publicationVisibilityMember';


/**
 * Ajustes de visibilidad del historial de publicaciones del usuario actual.
 */
export interface PublicationVisibilitySettingsResponse { 
    /**
     * Resto de miembros del grupo y su visibilidad sobre el usuario actual.
     */
    members: Array<PublicationVisibilityMember>;
}

