/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tipo de autor: interno (usuario registrado) o externo (no registrado).
 */
export const PublicationAuthorType = {
    Internal: 'INTERNAL',
    External: 'EXTERNAL'
} as const;
export type PublicationAuthorType = typeof PublicationAuthorType[keyof typeof PublicationAuthorType];

