/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Estado del ciclo de vida de la publicación.
 */
export const PublicationStatus = {
    Planned: 'PLANNED',
    Submitted: 'SUBMITTED',
    UnderReview: 'UNDER_REVIEW',
    MinorRevision: 'MINOR_REVISION',
    MajorRevision: 'MAJOR_REVISION',
    Rejected: 'REJECTED',
    Accepted: 'ACCEPTED',
    Published: 'PUBLISHED'
} as const;
export type PublicationStatus = typeof PublicationStatus[keyof typeof PublicationStatus];

