/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicationStatus } from './publicationStatus';


export interface PublicationResponse { 
    id: string;
    title: string;
    groupId: string;
    journalId: string;
    /**
     * Nombre del journal asociado.
     */
    journalName?: string;
    'abstract'?: string;
    doi?: string;
    status: PublicationStatus;
    createdBy: string;
    createdAt: string;
}
export namespace PublicationResponse {
}


