/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupRole } from './groupRole';


/**
 * Otro miembro del grupo y si puede ver el historial de publicaciones del usuario actual. 
 */
export interface PublicationVisibilityMember { 
    /**
     * Unique identifier of the member.
     */
    userId: string;
    /**
     * First name of the member.
     */
    firstName: string;
    /**
     * Last name of the member.
     */
    lastName: string;
    /**
     * Email of the member.
     */
    email: string;
    role: GroupRole;
    /**
     * URL of the member\'s profile image.
     */
    profileImageUrl: string;
    /**
     * Whether this member can currently see the user\'s publication history.
     */
    canSee: boolean;
    /**
     * Whether visibility for this member cannot be changed (always true for group administrators, who can always see everything). 
     */
    locked: boolean;
}
export namespace PublicationVisibilityMember {
}


