/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Reenvío de una publicación rechazada a otro journal. Solo aplica a publicaciones en estado REJECTED y el journal destino debe ser distinto del actual.
 */
export interface ResubmitPublicationRequest { 
    /**
     * Journal destino al que se reenvía la publicación. Debe ser distinto del actual.
     */
    journalId: string;
}

