/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SendInvitationRequest { 
    /**
     * Unique identifier of the user to be invited.
     */
    inviteeUserId: string;
}

