/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupRole } from './groupRole';


export interface UpdateGroupMemberRoleRequest { 
    role: GroupRole;
}
export namespace UpdateGroupMemberRoleRequest {
}


