/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicationAuthorInput } from './publicationAuthorInput';


/**
 * Campos editables de una publicación. El journal/grupo, el estado y el DOI no se pueden modificar tras la creación.
 */
export interface UpdatePublicationRequest { 
    /**
     * Título de la publicación. Obligatorio.
     */
    title: string;
    /**
     * Resumen de la publicación.
     */
    'abstract'?: string;
    /**
     * Co-autores de la publicación, en orden. El creador se mantiene siempre como autor interno.
     */
    authors?: Array<PublicationAuthorInput>;
}

