/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdatePublicationVisibilityRequest { 
    /**
     * Whether the member can see the user\'s publication history. false hides it, true restores the default visibility. 
     */
    canSee: boolean;
}

