/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PublicationAuthorInput } from './publicationAuthorInput';


/**
 * Campos editables de una publicación. El journal/grupo y el estado no se pueden modificar desde aquí. El DOI solo puede establecerse cuando la publicación está en estado PUBLISHED.
 */
export interface UpdatePublicationRequest { 
    /**
     * Título de la publicación. Obligatorio.
     */
    title: string;
    /**
     * Resumen de la publicación.
     */
    'abstract'?: string;
    /**
     * DOI de la publicación. Solo permitido cuando el estado es PUBLISHED.
     */
    doi?: string;
    /**
     * Co-autores de la publicación, en orden. El creador se mantiene siempre como autor interno.
     */
    authors?: Array<PublicationAuthorInput>;
}

