/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Resumen público de un usuario registrado, usado en búsquedas.
 */
export interface UserSummaryResponse { 
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    profileImageUrl: string;
}

