/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserUpdatePushNotificationRequest { 
    /**
     * Whether push notifications are enabled for the user.
     */
    pushNotifications: boolean;
}

