/**
 * REST API for RECORD
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileImageSignatureResponse { 
    signature: string;
    timestamp: string;
    api_key: string;
    cloud_name: string;
    transformation: string;
    folder: string;
}

