openapi: 3.0.3
info:
  title: REST API for RECORD
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /auth/login:
    $ref: "./auth/login.yaml"

  /auth/register:
    $ref: "./auth/register.yaml"

  /auth/refresh:
    $ref: "./auth/refresh.yaml"

  /auth/logout:
    $ref: "./auth/logout.yaml"

  /users/me:
    $ref: "./users/get-user.yaml"

  /users/me/update:
    $ref: "./users/update-user.yaml"

  /users/me/profile-image-signature:
    $ref: "./users/user-profile-image-signature.yaml"

  /users/me/update-push-notifications:
    $ref: "./users/update-push-notifications.yaml"

  /groups/create:
    $ref: "./groups/create.yaml"

  /groups/me:
    $ref: "./groups/list-groups.yaml"
